### ISSUE TITLE
Incorrect inputFrame and Aspect Ratio for Nintendo DS

### ISSUE THREAD

**Issue by vellbear** [noah978/Delta-Docs#10]
## Issue Summary
In the Delta-Docs under [Delta Custom Skins](https://noah978.gitbook.io/delta-docs/skins) > [Game Screens](https://noah978.gitbook.io/delta-docs/skins#game-screens) : 
The Full inputFrame & the Aspect Ratio sections in the table have incorrect values for the Nintendo DS console.

![nds_delta_docs_error](https://github.com/noah978/Delta-Docs/assets/70419875/b0d8ff5d-cad7-4d21-8812-08cac8791c4b)

## Current Values
Full inputFrame: 256x384
Aspect Ratio: 2:3

## Expected values
Full inputFrame: 256x192
Aspect Ratio: 4:3

**Comment by noah978** [comment]
This is perfectly normal and working as intended. If you look a bit below that table, it will make a special note about the DS. Its actually both the top and bottom frame together.

**Comment by vellbear** [comment]
Wow! My brain turned off. I was aware this was the case because I’ve actually read and reread your docs multiple times, because of a project I was planning out. I was looking at a .json file that was using 256x192 for the screen size and completely ignored the fact that it puts the top and bottom frame together. I don’t know how I didn’t put 2 and 2 together. Sorry for the misunderstanding, and I sincerely appreciate the response.
