### ISSUE TITLE
Rotating D-Pad

### ISSUE THREAD

**Issue by GreedFeal** [noah978/Delta-Docs#23]
Hello. I'm very excited about Delta app and like to draw a skin for it. Can I rotate D-Pad to improve playing in isometric games. I'm only need 10º to easy understanding destinations in FFTA. Sorry for mistakes. In attachment my future skin in work.

![IMG_2639](https://github.com/user-attachments/assets/02aecde1-dea4-463b-ac30-9e98a6dd6962)
![IMG_2640](https://github.com/user-attachments/assets/548a066a-b876-4812-b966-e6114923a3ce)

**Comment by noah978** [comment]
You can definitely rotate the image of the dpad (what you’ve done in the image is perfectly fine). However, the underlying “mapping” of where the touch buttons are cannot be rotated to match exactly. But you can still move the touch buttons to roughly fit your image and still have a relatively good touch screen experience.

**Comment by GreedFeal** [comment]
Thank you. I think it's not a big problem
